import { Contact } from '@/components/dashboard/types';

export const mockContacts: Contact[] = [
  {
    id: '1',
    domain: 'example.com',
    niche: 'Business',
    priceFromBacklinker: 250,
    email1: 'john@example.com',
    name1: 'John Doe',
    email2: 'jane@example.com',
    name2: 'Jane Doe',
    email3: undefined,
    name3: undefined,
    status: 'pending',
    emailAccount: 'outreach@linkops.com',
    currency: 'EUR',
    standardPrice: 250,
    gamblingPrice: 350,
    negotiatedPrice: 225,
    acceptCasino: true,
    acceptBetting: false,
    sponsored: false,
    linkTerm: '6 months',
    dateConfirmed: undefined,
    notes: 'Good domain authority',
    contentGuidelines: 'Professional tone, 500 words min',
    reply: 'pending',
  },
  {
    id: '2',
    domain: 'casino-hub.com',
    niche: 'Casino',
    priceFromBacklinker: 500,
    email1: 'contact@casino-hub.com',
    name1: 'Alex Smith',
    email2: undefined,
    name2: undefined,
    email3: undefined,
    name3: undefined,
    status: 'confirmed',
    emailAccount: 'outreach@linkops.com',
    currency: 'EUR',
    standardPrice: 450,
    gamblingPrice: 600,
    negotiatedPrice: 425,
    acceptCasino: true,
    acceptBetting: true,
    sponsored: false,
    linkTerm: '1 year',
    dateConfirmed: '2026-04-15',
    notes: 'Fast response, easy to work with',
    contentGuidelines: 'Gaming industry standard',
    reply: 'yes',
  },
  {
    id: '3',
    domain: 'techblog.org',
    niche: 'Technology',
    priceFromBacklinker: 180,
    email1: 'editor@techblog.org',
    name1: 'Sarah Chen',
    email2: 'submissions@techblog.org',
    name2: 'Editorial Team',
    email3: undefined,
    name3: undefined,
    status: 'negotiation',
    emailAccount: 'outreach@linkops.com',
    currency: 'EUR',
    standardPrice: 200,
    gamblingPrice: 250,
    negotiatedPrice: undefined,
    acceptCasino: false,
    acceptBetting: false,
    sponsored: true,
    linkTerm: '3 months',
    dateConfirmed: undefined,
    notes: 'Waiting on their counter offer',
    contentGuidelines: 'Tech-focused, no promotional tone',
    reply: 'pending',
  },
  {
    id: '4',
    domain: 'sportsbeat.net',
    niche: 'Sports',
    priceFromBacklinker: 320,
    email1: 'press@sportsbeat.net',
    name1: 'Mike Johnson',
    email2: undefined,
    name2: undefined,
    email3: undefined,
    name3: undefined,
    status: 'no_deal',
    emailAccount: 'outreach@linkops.com',
    currency: 'EUR',
    standardPrice: 300,
    gamblingPrice: 400,
    negotiatedPrice: undefined,
    acceptCasino: false,
    acceptBetting: true,
    sponsored: false,
    linkTerm: '',
    dateConfirmed: undefined,
    notes: 'Not interested in partnerships',
    contentGuidelines: 'Sports news format',
    reply: 'no',
  },
  {
    id: '5',
    domain: 'financialjournal.io',
    niche: 'Finance',
    priceFromBacklinker: 400,
    email1: 'contributors@financialjournal.io',
    name1: 'David Brown',
    email2: 'editor@financialjournal.io',
    name2: 'Lisa Wong',
    email3: undefined,
    name3: undefined,
    status: 'follow_up',
    emailAccount: 'outreach@linkops.com',
    currency: 'EUR',
    standardPrice: 380,
    gamblingPrice: 500,
    negotiatedPrice: undefined,
    acceptCasino: false,
    acceptBetting: false,
    sponsored: false,
    linkTerm: '4 months',
    dateConfirmed: undefined,
    notes: 'Sent follow-up email 2 days ago',
    contentGuidelines: 'Financial analysis focus',
    reply: 'pending',
  },
];
