import { Contact } from '@/components/dashboard/types'

export const mockContacts: Contact[] = [
  {
    id: '1',
    domain: 'example.com',
    website: 'https://example.com',
    niche: 'Business',
    contact: 'John Doe',
    email: 'john@example.com',
    status: 'start_outreach',
    price: undefined,
    tat: undefined,
    linkType: 'Guest Post',
    publishDate: undefined,
    liveUrl: undefined,
    notes: 'Initial outreach pending',
    outreachDate: undefined,
    followupDate: undefined,
    responseDate: undefined,
    paymentStatus: undefined,
  },
  {
    id: '2',
    domain: 'techblog.io',
    website: 'https://techblog.io',
    niche: 'Technology',
    contact: 'Sarah Smith',
    email: 'sarah@techblog.io',
    status: 'outreach_sent',
    price: undefined,
    tat: undefined,
    linkType: 'Sponsored Article',
    publishDate: undefined,
    liveUrl: undefined,
    notes: 'Outreach email sent',
    outreachDate: '2026-04-20',
    followupDate: undefined,
    responseDate: undefined,
    paymentStatus: undefined,
  },
  {
    id: '3',
    domain: 'business-today.net',
    website: 'https://business-today.net',
    niche: 'Business',
    contact: 'Mike Johnson',
    email: 'mike@business-today.net',
    status: 'send_followup',
    price: undefined,
    tat: undefined,
    linkType: 'Dofollow',
    publishDate: undefined,
    liveUrl: undefined,
    notes: 'Waiting for follow-up response',
    outreachDate: '2026-04-15',
    followupDate: '2026-04-25',
    responseDate: undefined,
    paymentStatus: undefined,
  },
  {
    id: '4',
    domain: 'newscentral.co.uk',
    website: 'https://newscentral.co.uk',
    niche: 'News',
    contact: 'Emma Davis',
    email: 'emma@newscentral.co.uk',
    status: 'response_received',
    price: undefined,
    tat: undefined,
    linkType: 'Guest Post',
    publishDate: undefined,
    liveUrl: undefined,
    notes: 'Contact responded positively',
    outreachDate: '2026-04-10',
    followupDate: '2026-04-18',
    responseDate: '2026-04-24',
    paymentStatus: undefined,
  },
  {
    id: '5',
    domain: 'digital-marketing.com',
    website: 'https://digital-marketing.com',
    niche: 'Marketing',
    contact: 'Alex Wilson',
    email: 'alex@digital-marketing.com',
    status: 'under_negotiation',
    price: 500,
    tat: '5 days',
    linkType: 'Sponsored + Dofollow',
    publishDate: undefined,
    liveUrl: undefined,
    notes: 'Terms being negotiated',
    contentGuideline: 'Article must be 800+ words, include 2 dofollow links, no competitor mentions.',
    outreachDate: '2026-04-05',
    followupDate: '2026-04-12',
    responseDate: '2026-04-20',
    paymentStatus: undefined,
  },
  {
    id: '6',
    domain: 'innovation-hub.org',
    website: 'https://innovation-hub.org',
    niche: 'Technology',
    contact: 'Lisa Anderson',
    email: 'lisa@innovation-hub.org',
    status: 'approved',
    price: 750,
    tat: '3 days',
    linkType: 'Guest Post + Dofollow',
    publishDate: undefined,
    liveUrl: undefined,
    notes: 'Deal approved, awaiting payment',
    outreachDate: '2026-03-28',
    followupDate: '2026-04-05',
    responseDate: '2026-04-10',
    paymentStatus: undefined,
  },
  {
    id: '7',
    domain: 'growth-strategies.net',
    website: 'https://growth-strategies.net',
    niche: 'Business',
    contact: 'Robert Brown',
    email: 'robert@growth-strategies.net',
    status: 'payment_sent',
    price: 600,
    tat: '4 days',
    linkType: 'Sponsored Guest Post',
    publishDate: undefined,
    liveUrl: undefined,
    notes: 'Payment sent, awaiting publication',
    outreachDate: '2026-03-20',
    followupDate: '2026-03-28',
    responseDate: '2026-04-02',
    paymentStatus: 'paid',
  },
  {
    id: '8',
    domain: 'industry-leaders.io',
    website: 'https://industry-leaders.io',
    niche: 'Technology',
    contact: 'Jennifer Martinez',
    email: 'jennifer@industry-leaders.io',
    status: 'live',
    price: 800,
    tat: '2 days',
    linkType: 'Featured Guest Post',
    publishDate: '2026-04-22',
    liveUrl: 'https://industry-leaders.io/guest-post-link-insertion',
    notes: 'Live on site',
    outreachDate: '2026-03-15',
    followupDate: '2026-03-22',
    responseDate: '2026-03-28',
    paymentStatus: 'paid',
  },
]
